apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: willapp-ingress
  namespace: dev
spec:
  rules:
    - http:
       paths:
       - pathType: Prefix
         path: /
         backend:
           service:
             name: argocd-wilapp
             port:
               number: 80
